obj-y += foo.S

#PROJECT = foo
#CPU ?= cortex-m3
#BOARD ?= stm32vldiscovery

#qemu:
#	arm-none-eabi-as -mthumb -mcpu=$(CPU) -c foo.S -o foo.o
#	arm-none-eabi-ld -Tmap.ld foo.o -o foo.elf
#	qemu-system-arm -S -M $(BOARD) -cpu $(CPU) -kernel $(PROJECT).elf 

#clean:
#	rm -rf *.out *.elf *.lst *.debug *.o
	
